services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
